##################
name: Super-Linter


# State events that triggers workflow yaml file, which will run all jobs in workflow
# Start the job on all pushes

on: push
# single job below with two steps
jobs:
  super-lint:
  # Name the Job
    name: Lint code base
    # set the agent to run on ubuntu
    # runs on parameter, runner, aka container env
    runs-on: ubuntu-latest  
    
    # Load all steps
    steps:
     # Checkout the code base #
      - name: Checkout code
        uses: actions/checkout@v2
        
      # linter is a check on syntax, make sure standards of the lanquage are met
      - name: Run Super-Linter 
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       
